import chroma from "chroma-js";
export default {
  colorBox: {
    width: " 20%",
    height: (props) => (props.showLink ? " 25%" : "50%"),
    cursor: " pointer",
    display: "inline-block",
    position: "relative",
    margin: "0 auto",
    marginBottom: "-3.5px",
    "&:hover button": {
      opacity: " 1",
    },
  },

  copyButton: {
    width: " 100px",
    height: " 30px",
    position: "absolute",
    display: " inline-block",
    cursor: "pointer",
    top: "40%",
    left: "40%",
    outline: " none",
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    color: "azure",
    fontSize: "1rem",
    lineHeight: " 20px",
    textTransform: " uppercase",
    border: "none",
    opacity: "0",
  },
  copyText: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.5 ? "black" : "white",
  },
  copyColor: {
    color: (props) =>
      chroma(props.background).luminance() <= 0.08 ? "white" : "black",
  },
  copyMsg: {
    position: " fixed",
    zIndex: "0",
    opacity: "0",
    justifyContent: " center",
    alignItems: " center",
    color: " blue",
    transform: " scale(0.1)",
    top: "0",
    right: " 0",
    bottom: " 0",
    left: " 0",
    display: "flex",
    flexDirection: "column",
    fontSize: "5rem",
    "& p": {
      fontWeight: " 400",
      textShadow: " 1px 2px whitesmoke",
      backgroundColor: " rgba(255, 255, 255, 0.5)",
      textAlign: "center",
      width: "100%",
      color: " white",
      padding: " 1rem",
      marginBottom: " 0",
    },
    "& h4": {
      fontSize: " 4rem",
      color: " aliceblue",
    },
  },
  show: {
    opacity: " 1",
    zIndex: " 25",
    transform: " scale(1)",
    transition: " all 0.5s ease-in-out",
    transitionDelay: "0.3",
  },
  copyPalette: {
    opacity: " 0",
    zIndex: " 0",
    width: " 100%",
    height: "100%",
    transition: " transform 0.5s ease-in-out",
  },
  show1: {
    opacity: " 1",
    zIndex: " 5",
    position: "absolute",
    transform: "scale(20)",
  },
  learnMore: {
    color: " wheat",
    backgroundColor: " rgba(255, 255, 255, 0.3)",
    right: "0px",
    position: "absolute",
    bottom: " 0px",
    height: " 30px",
    textAlign: "center",
    lineHeight: "30px",
  },
  copyContent: {
    position: "absolute",
    left: " 0px",
    bottom: "0px",
    textTransform: " uppercase",
    fontSize: " 12px",
    color: "darkred",
    letterSpacing: "1px",
    padding: " 10px",
    width: " 100%",
  },
};
